CREATE DATABASE catalog_of_things;

CREATE TABLE Author(
  id INT GENERATED ALWAYS AS IDENTITY,
  first_name VARCHAR(255),
  last_name  VARCHAR(255),
  PRIMARY KEY(id)
);

CREATE TABLE Genre (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) 
);

CREATE TABLE Label (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL
);

CREATE TABLE Game(
  id INT GENERATED ALWAYS AS IDENTITY,
  genre_id INT,
  author_id INT,
  source_id INT,
  label_id INT,
  archived BOOLEAN,
  multiplayer VARCHAR(3),
  last_played_at  DATE,
  PRIMARY KEY(id),
  CONSTRAINT fk_genre_id FOREIGN KEY(genre_id) REFERENCES Genre (id),
  CONSTRAINT fk_author_id FOREIGN KEY(author_id) REFERENCES Author(id),
  CONSTRAINT fk_label_id FOREIGN KEY(label_id) REFERENCES Label(id)
);

CREATE INDEX multi_data_index ON Game(genre_id, author_id, label_id)

CREATE TABLE MusicAlbum (
  id SERIAL PRIMARY KEY,
  publish_date DATE,
  genre_id INT,
  author_id INT,
  label_id INT,
  on_spotify BOOLEAN,
  FOREIGN KEY (genre_id) REFERENCES Genre(id),
  FOREIGN KEY (author_id) REFERENCES Author(id),
  FOREIGN KEY (label_id) REFERENCES Label(id)
);

CREATE INDEX multi_data_index ON MusicAlbum(genre_id, author_id, label_id)

CREATE TABLE Books (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  genre_id INT,
  author_id INT,
  label_id INT,
  cover_state VARCHAR(10) NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  publish_date DATE,
  FOREIGN KEY (genre_id) REFERENCES Genre(id),
  FOREIGN KEY (author_id) REFERENCES Author(id),
  FOREIGN KEY (label_id) REFERENCES Label(id)
);

CREATE INDEX multi_data_index ON Books(genre_id, author_id, label_id)
